-- Database initialization script for Email Dashboard API
-- Run this script in your SAP HANA database to create the required table

-- Create the users table
CREATE TABLE "YOUR_SCHEMA"."YOUR_USERS_TABLE" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) NOT NULL UNIQUE,
    password NVARCHAR(255) NOT NULL,
    role NVARCHAR(20) NOT NULL CHECK (role IN ('admin', 'user')),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON "YOUR_SCHEMA"."YOUR_USERS_TABLE" (email);
CREATE INDEX idx_users_role ON "YOUR_SCHEMA"."YOUR_USERS_TABLE" (role);

-- Insert a default admin user (password: admin123)
-- Note: The password hash below is for 'admin123' - change this in production!
INSERT INTO "YOUR_SCHEMA"."YOUR_USERS_TABLE" (fullName, email, password, role)
VALUES (
    'System Administrator',
    'admin@example.com',
    '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/NhPcQ1u', -- admin123
    'admin'
);

-- Verify the table was created successfully
SELECT * FROM "YOUR_SCHEMA"."YOUR_USERS_TABLE";

-- Instructions:
-- 1. Replace "YOUR_SCHEMA" with your actual schema name
-- 2. Replace "YOUR_USERS_TABLE" with your actual table name
-- 3. Update the .env file with the correct schema and table names
-- 4. The default admin credentials are:
--    Email: admin@example.com
--    Password: admin123
--    Change these credentials immediately in production!
